### ISSUE TITLE
Paragraph navigation

### ISSUE THREAD

**Issue by rafmsou** [soulshined/Navigator#1]
Hey, I saw your post on reddit and I'm using the extension for a bit. 

One nice addition to it would be "paragraph" navigation or "block" navigation as we call it. 
I used to use it on vim:

> } 
> Jump forward one paragraph.
> { 
> Jump backward one paragraph.
> 

There's a vscode extension for that too: https://marketplace.visualstudio.com/items?itemName=sashaweiss.block-travel

Would be cool to have something like that in this extension.

**Comment by soulshined** [comment]
Great idea @rafmsou practical and I love the recommended keybind. Thanks for the visual reference too. 

Is the expectation to actually jump to the next empty line always? I feel like the description of that extension leaves room for interpretation. 
I tried the extension out and it appears it just jumps to the first found empty line. Although I suppose technically a paragraph is separated by newlines. To me, I would anticipate if there was actually a 'block', it would jump it completely; take this example:

```js
1.
2.  /* foo method */
3.  function foo(foobar) {
4.    const foos = ['bar', 'baz'];
5.    
6.    return foos.indexOf(foobar) >= 0;
7.  }
8. █
```

That extension doesn't jump the block/paragraph to line #1, it would just go to line #5. 

Is this how it works in vim as well? Empty lines are synonymous with paragraphs? If so, that's not a problem and I could implement that relatively quickly. Just want to clarify the expectation. Thanks

--- 

As a workaround interim you could jump 'symbols' using the default `CTRL + ;` chord `CTRL + UpArrow/DownArrow` and you can specify the symbols per language. Although it doesn't support selection yet, I would love to add support for that as well.

**Comment by rafmsou** [comment]
> Is this how it works in vim as well? Empty lines are synonymous with paragraphs?

Yes, so, in your example it should go to line #1. I just gave the extension as an example but I never actually used it.

What I would suggest is that `CTRL + ;` `CTRL + }` would go to the next empty line and `CTRL + ;` `CTRL + {` would go to the previous empty line.

**Comment by soulshined** [comment]
Ah, so if the expectation is to go to line #1, then `go to next/prev symbol` is effectively the same thing but it has some limitations (the biggest one being it relies on symbols); you could just rebind the keybind to `CTRL+{` and add all symbol kinds. I will just need to update and add support for choosing if the selection goes on the symbol name like it currently does or above it where the comments are like you expect. I can work that out tomorrow or Thursday.

If that isn't acceptable and you are thinking it should rely on text/syntax and not symbols, the only difficult thing about that ask is doing it in a language-agnostic manner. For example, javascript has obvious boundaries, whereas HTML is not as obvious and a 'paragraph' can mean many things; same for obscure languages or SCSS like preprocessors. I would need some more time to hash it out and make sure it's proper

**Comment by rafmsou** [comment]
Sorry I didn't completely understand your question, in your example it should go to **line #5 and then line #1**. 
So yes, it needs to go to line #5 first when activating the `prevParagraph` command, not to line #1 directly.

An empty line would be the start/end of a paragraph and navigation would pass through it.

**Comment by soulshined** [comment]
Got it! Makes sense now. Thank you

**Comment by soulshined** [comment]
@rafmsou See changes. I had to bind it to `CTRL+[` that way if users wanted to select the text they could use `CTRL+SHIFT+[`, but you are more than welcome to rebind them or invert them to suit your needs.

**Comment by rafmsou** [comment]
@soulshined Sweet! Nice job making it repeatable.
One question though, did you make it required to type `<ESC>` after the motion to release control back to the editor?
I can't move the cursor or type anything after the command...

**Comment by soulshined** [comment]
Yeah @rafmsou, my design philosophy is to not cancel navigator focus unless the user explicitly does it or they execute a command that takes input and has an 'end' (match/line/char found); for a couple of reasons:
- the biggest being that it's really the only way I know when a user is done 'navigating' so I can clean the state and not interfere with the normal vscode keybinds/states. Unfortunately, vscode's API doesn't provide keydown/keyup event handlers, so there's really no way for devs to know when someone is done typing, without being creative. An example of how to work around that, is we have to create commands with args or keybinds specifically with the shift modifier just to know if they are pressing shift, same for ctrl and backspace/delete etc. 
- limit confusion & maintain continuity (personal friends testing this before I published it stated they were confused or didn't remember if they had an active Navigator and accidentally executed 'navigator commands' in a non-navigator context - this is ultimately where the inactiveForeground/activeForeground pattern was birthed)
- this allows users to quickly execute another command without worrying about reactivating, should they choose so
   For example, jumping to symbols doesn't accept input just like this command so the idea is the user can jump to another symbol and then submit a regexp or whatever the active command is without doubling down on `CTRL + ;` and `ESC` before each symbol.

Since this command doesn't have an 'end' either, there's no _reliable_ way for me to know when the user is done that I can think of. If you have any ideas I'm all ears.

With that said, if you really don't like it this way you can remove the `navigator.isInputMode` context in your keybinds' when expression. 

From:
```
{
  "key": "ctrl+]",
  "command": "navigator.jump-to-next-paragraph",
  "when": "editorTextFocus && navigator.isInputMode"
}
```
To:
```
{
  "key": "ctrl+]",
  "command": "navigator.jump-to-next-paragraph",
  "when": "editorTextFocus"
}
```

There are some caveats to this, I'm pretty sure it will conflict with other commands with the same priority (untested) and keybind. I think it defaults to indent line. I also haven't tested how this impacts navigator logic or control flow in general, but just offering it for brevity. Definitely something I need to review for correctness.

Or you could use the already provided `repeat last command` (`CTRL + SHIFT + ;`) at any time to repeat the last command (Probably not ideal for this use-case, but it's a thing)

I'm open to discussions on a new design philosophy, but in this case, I'm mostly limited by vscode's API for now.

**Comment by rafmsou** [comment]
@soulshined I got your point about the design decision. 
It makes sense now that I think about some possibilities that this opens up. Thanks for the clarification 😃.

I'm still not that familiar with how VSCode handles key combos in extensions, I might learn a bit more about it before suggesting anything.

One last thing though (off topic), is there also an explicit reason not to have the search cyclic? By that I mean, when you reach the last occurrence of a search term, you continue searching from the beginning of the file?

**Comment by soulshined** [comment]
@rafmsou Nope, I have no good counter for that one :) Probably because I personally don't use it, and that's the downfall of biased coding. I'll add that option in too! Good catch
